### ISSUE TITLE
[feature] Add parser for Wireguard

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/netdiff#100]
This wireguard-tools script helps explaining the output of the `dump` command and how to parse it:
https://github.com/WireGuard/wireguard-tools/blob/master/contrib/json/wg-json

I think we should implement something similar in python and generate the network graph.

We can pass an argument which lets us choose whether the primary ID of the nodes should be the IP address or the public key, for consistency with the other parsers I would use the IP as default.

**Comment by codesankalp** [comment]
> We can pass an argument which lets us choose whether the primary ID of the nodes should be the IP address or the public key, for consistency with the other parsers I would use the IP as default.

By IP address here, do you mean allowedIps in wireguard (` wg show all dump`)?

**Comment by nemesisdesign** [comment]
I think the netjson ID would have to be necessarily the public key because.. we can show the address as a secondary address and as the label
