### ISSUE TITLE
[openvpn] Ignore UNDEF nodes

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/netdiff#59]
**reserved for GCI**

Sometimes OpenVPN will report nodes which are named `UNDEF` (which stands for undefined).
We should ignore these nodes. Don't forget to write a test for this change :-)

[Why this UNDEF shows up in the first place? ](https://openvpn.net/archive/openvpn-users/2004-08/msg00116.html)

**Comment by unsuitable001** [comment]
can it be done by adding something like `if (node.name == UNDEF) then ignore or start the loop from first`
I'm just trying to write some pseudocode above :smile: 

Guide me. If I can, I may take the task
